spring.application.name=mcc-backend
spring.main.allow-circular-references=true

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/mcc
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# JWT Configuration
jwt.secret=1c029f6b5a56cc4ebdf3b4347fbdd6444af72eb15b59cee3e3cd5f6a225cfa2651fa7f5b53437e849854372522009fcc0e6950ad14a88aedbae7aa4a498b0129
jwt.expiration=86400000
jwt.token-prefix=Bearer 
jwt.header-string=Authorization

# Security Configuration
security.public-paths=/api/auth/login,/api/auth/register

# Response Messages
response.error.unauthorized=Unauthorized - No token provided
response.error.token-expired=Token has expired
response.error.invalid-token=Unauthorized - Invalid token
response.success.valid-token=Valid token

